apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsimple-api
  namespace: shopsimple
  labels:
    app.kubernetes.io/part-of: shopsimple
    app.kubernetes.io/component: api
  annotations:
    eks.amazonaws.com/role-arn: "${AWS_ROLE_ARN}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsimple-frontend
  namespace: shopsimple
  labels:
    app.kubernetes.io/part-of: shopsimple
    app.kubernetes.io/component: frontend

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopsimple-worker
  namespace: shopsimple
  labels:
    app.kubernetes.io/part-of: shopsimple
    app.kubernetes.io/component: worker
  annotations:
    eks.amazonaws.com/role-arn: "${AWS_ROLE_ARN}"
