apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: shopsimple
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: shopsimple
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 4001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: shopsimple
    app.kubernetes.io/component: worker
