apiVersion: v1
kind: Namespace
metadata:
  name: shopsimple
  labels:
    app.kubernetes.io/part-of: shopsimple
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
