apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopsimple

resources:
  - namespaces/
  - rbac/
  - configmap.yaml
  - secrets.yaml
  - frontend/
  - api/
  - worker/

commonLabels:
  app.kubernetes.io/part-of: shopsimple
  app.kubernetes.io/managed-by: kustomize
