apiVersion: v1
kind: Secret
metadata:
  name: shopsimple-db-credentials
  namespace: shopsimple
type: Opaque
stringData:
  url: "postgresql://postgres:postgres@localhost:5432/shopsimple"

---
apiVersion: v1
kind: Secret
metadata:
  name: shopsimple-redis-credentials
  namespace: shopsimple
type: Opaque
stringData:
  url: "redis://localhost:6379"
